import type { Metadata } from "next";
import "../globals.css";
import { FiShoppingCart } from "react-icons/fi";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <header className="px-10 py-6 flex gap-10 items-center">
          <h1 className="flex-1">Aqui é onde ficar a logo: ODERCO GAMER</h1>
          <div className="!w-10 !h-8 relative">
            <FiShoppingCart size={28} color="#71717a" className="bottom-0 absolute" />
            <div className="h-4 w-4 text-xs rounded-full bg-info text-background flex items-center justify-center absolute top-0 right-0">4</div>
          </div>
          <Button variant={"info"}>Entrar</Button>
        </header>
        {children}
      </body>
    </html>
  );
}
