"use client";

import { Metadata } from "next";
import "../../globals.css";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";

const metadata: Metadata = {
  title: "Catalog",
  description: "Generated by create next app",
};

export default function RegisterProductLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <div className="w-full h-screen bg-background !overflow-hidden">
          <SessionProvider>
            {children}
          </SessionProvider>
          <Toaster />
        </div>
      </body>
    </html>
  );
}