import { Metadata } from "next";
import "../../../globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Register Product",
  description: "Generated by create next app",
};

export default function RegisterProductLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="w-full h-screen bg-background">
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}