import { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="w-full h-screen bg-background flex items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}